version: '3.7'
services:
  prometheus:
    image: "prom/prometheus"
    network_mode: host
#    ports:
#      - "9090:9090"
    volumes:
      - ./etc/prometheus.yml:/etc/prometheus/prometheus.yml
    container_name: prometheus
  grafana:
    image: "grafana/grafana"
    network_mode: host
    volumes:
      - ./etc/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./etc/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./etc/dashboards:/var/lib/grafana/dashboards
      - ./etc/grafana.ini:/etc/grafana/grafana.ini
#    ports:
#      - "3000:3000"
    container_name: grafana
#  rabbitmq:
#    image: "rabbitmq:3-management"
#    network_mode: host
#    container_name: rabbitmq
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock